# git
alias g='git'
alias ga='git add'
alias gau='git add -u'
alias gcv='git commit -v'
alias gdc='git diff --cached'
alias gdi='git diff'
alias gf='git fetch --prune'
alias gg='git grep -i -P'
alias gp='git plog -10'
alias gr='git fetch --prune --all && git checkout origin/HEAD && git plog -10 && git status'
alias gs='git switch -d origin/HEAD'
alias gst='git status'

# terraform
alias t='terraform'
alias ta='terraform apply'
alias te='terraform init --upgrade && terraform fmt && terraform plan'
alias tf='terraform fmt'
alias ti='terraform init'
alias tiu='terraform init --upgrade'
alias to='terraform output'
alias tp='terraform plan'
alias ts='terraform state'
